{ pkgs, ... }:
{
  home.packages = [ pkgs.niri ];
  xdg.configFile."niri/config.kdl".source = ./config/config.kdl;
  xdg.configFile."niri/bind.kdl".source = ./config/bind.kdl;
  xdg.configFile."niri/input.kdl".source = ./config/input.kdl;
  xdg.configFile."niri/layout.kdl".source = ./config/layout.kdl;
  xdg.configFile."niri/output.kdl".source = ./config/output.kdl;
  xdg.configFile."niri/rules.kdl".source = ./config/rules.kdl;
  # noctalia.kdl is generated by noctalia-shell at runtime
}
